export const colorPanelColors = [
  "#33333355",
  "#ff00e655",
  "#9000ff55",
  "#0088ff55",
  "#38ffe155",
  "#00ff2f55",
  "#ffcc0055",
  "#ff893655",
  "#ff303055",
];

export const themes = {
  dark: {
    accent: "#fff",
    background: "#25292b",
    backgroundSecondary: "#1e2123",
    backgroundGrey: "#333",
    backgroundDark: "#000",
    accentColored: "#80266e",
    accentColoredBright: "#ed39c9",
    accentColoredDark: "#9b2e85",
    delCol: "#802626",
    delActiveCol: "#9b2e2e",
    cardBgCol: "#3f4447",
    cardBgActiveCol: "#434b4f",
    columnBgColor: "#2f3437",
    columnBorderColor: "#9b2e85",
    shadow: "rgba(0, 0, 0, 0.2)",
    panelColors: colorPanelColors,
		kanbieLogoHueRotate: 0,
		kanbieLogoGrayscale: 0,
  },
  light: {
    accent: "#333",
    background: "#f5f5f5",
    backgroundSecondary: "#ededed",
    backgroundGrey: "#fff",
    backgroundDark: "#fff",
    accentColored: "#ecdaed",
    accentColoredBright: "#ed39c9",
    accentColoredDark: "#ed39c9",
    delCol: "#ff8080",
    delActiveCol: "#f54e4e",
    cardBgCol: "#ededed",
    cardBgActiveCol: "#bdbdbd",
    columnBgColor: "#fff",
    columnBorderColor: "#ed39c9",
    shadow: "rgba(0, 0, 0, 0)",
    panelColors: colorPanelColors,
		kanbieLogoHueRotate: "0deg",
		kanbieLogoGrayscale: 0,
  },
	blue: {
    accent: "#333",
    background: "#f5f5f5",
    backgroundSecondary: "#ededed",
    backgroundGrey: "#fefefe",
    backgroundDark: "#fff",
    accentColored: "#E3F2FD",
    accentColoredBright: "#4285f4",
    accentColoredDark: "#4285f4",
    delCol: "#ff8080",
    delActiveCol: "#f54e4e",
    cardBgCol: "#ededed",
    cardBgActiveCol: "#bdbdbd",
    columnBgColor: "#fff",
    columnBorderColor: "#4285f4",
    shadow: "rgba(0, 0, 0, 0)",
    panelColors: colorPanelColors,
		kanbieLogoHueRotate: "270deg",
		kanbieLogoGrayscale: 0,
  },
	monodark: {
		accent: "#fff",
    background: "#333",
    backgroundSecondary: "#1e2123",
    backgroundGrey: "#555",
    backgroundDark: "#333",
    accentColored: "#555",
    accentColoredBright: "#777",
    accentColoredDark: "#666",
    delCol: "#802626",
    delActiveCol: "#9b2e2e",
    cardBgCol: "#444",
    cardBgActiveCol: "#777",
    columnBgColor: "#333",
    columnBorderColor: "#ddd",
    shadow: "rgba(0, 0, 0, 0)",
    panelColors: colorPanelColors,
		kanbieLogoHueRotate: "0deg",
		kanbieLogoGrayscale: 1,
  },
	monolight: {
    accent: "#333",
    background: "#f5f5f5",
    backgroundSecondary: "#ededed",
    backgroundGrey: "#fefefe",
    backgroundDark: "#fff",
    accentColored: "#ddd",
    accentColoredBright: "#666",
    accentColoredDark: "#555",
    delCol: "#ff8080",
    delActiveCol: "#f54e4e",
    cardBgCol: "#ededed",
    cardBgActiveCol: "#bdbdbd",
    columnBgColor: "#f5f5f5",
    columnBorderColor: "#333",
    shadow: "rgba(0, 0, 0, 0)",
    panelColors: colorPanelColors,
		kanbieLogoHueRotate: "270deg",
		kanbieLogoGrayscale: 1,
  }
}
